default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password:
  host: <%= ENV['HF_DB_HOST'] %>
  socket: /tmp/mysql.sock
  database: hipchat_exporter

test:
  <<: *default
  database: hipchat_exporter_test
